#!/bin/sh
echo "deb http://fr.archive.ubuntu.com/ubuntu jammy main restricted universe multiverse" > /etc/apt/sources.list
echo "deb-src http://fr.archive.ubuntu.com/ubuntu jammy main restricted universe multiverse" >> /etc/apt/sources.list
echo "deb http://fr.archive.ubuntu.com/ubuntu jammy-security main restricted universe multiverse" >> /etc/apt/sources.list
echo "deb-src http://fr.archive.ubuntu.com/ubuntu jammy-security main restricted universe multiverse" >> /etc/apt/sources.list
echo "deb http://fr.archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse" >> /etc/apt/sources.list
echo "deb-src http://fr.archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse" >> /etc/apt/sources.list
echo "deb [trusted=yes] https://github.com/amidevous/xtream-ui-ubuntu20.04/raw/master/package/Ubuntu jammy main" >> /etc/apt/sources.list
apt-get update
apt-get -y dist-upgrade
